### PR TITLE
Hyperv support for tex

### PR DESCRIPTION
**Pull request by nkrinner**
As Jiri is in Vancouver I am taking over from https://github.com/crowbar/barclamp-ceilometer/pull/190
where this has already been reviewed.

### CODE REVIEW

**Comment by tboerger** [comment]
+1

**Comment by tboerger** [comment]
Already reviewed on #190, merging

**Comment by vuntz** [comment]
@nkrinner you need to add a commit like https://github.com/jsuchome/barclamp-ceilometer/commit/4e72e87a19a2965117300d314c0eae0b287b8565 too for tex.

**Comment by nkrinner** [comment]
@vuntz I somehow missed that, done now in https://github.com/crowbar/barclamp-ceilometer/pull/196

**Pull request merged**
