### PR TITLE
bump schema revision

### PR DESCRIPTION
**Pull request by nkrinner**
(cherry picked from commit 4e72e87a19a2965117300d314c0eae0b287b8565)

Add forgotten schema migration...

### CODE REVIEW

**Comment by rsalevsky** [comment]
Maybe I missed something but why is this needed?

**Comment by tboerger** [comment]
+1

**Comment by tboerger** [comment]
> Maybe I missed something but why is this needed?

Because @nkrinner missed the commit for another backport to tex.

**Comment by rsalevsky** [comment]
+1

**Comment by nkrinner** [comment]
@rsalevsky I updated the schema in https://github.com/crowbar/barclamp-ceilometer/pull/196#issuecomment-103921686 but forgot to update the schema revision there somehow.

**Pull request merged**
