### PR TITLE
[backport] Support ceilometer-agent role deployemt on hyperv nodes

### PR DESCRIPTION
**Pull request by jsuchome**
Backport of https://github.com/crowbar/barclamp-ceilometer/pull/188

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
Please use `cherry-pick -x` when backporting (to have a mention of the old commit in the log message).

**Comment by tboerger** [comment]
```cherry-pick -x```, afterwards +1

**Comment by nkrinner** [comment]
See https://github.com/crowbar/barclamp-ceilometer/pull/194

**Pull request closed without merging**
