### PR TITLE
Adapt config file to the one in package.

### PR DESCRIPTION
**Pull request by jsuchome**
fork = true is in sync with current systemctl service file.

### CODE REVIEW

**Comment by tboerger** [comment]
Why not... :+1:

**Comment by aplanas** [comment]
+1

**Comment by jsuchome** [comment]
@vuntz @aplanas do you think this change should be made for SLE12 nodes only? 

Or, we don't have to care as Cloud6 is SLE12-only? (unless ceilometer-server is deployed to compute node which stays with SLE11...)

**Comment by vuntz** [comment]
> @vuntz @aplanas do you think this change should be made for SLE12 nodes only? 

Does it hurt on SLE11? :-) If yes, then I would make it SLE12-only (or more correctly: systemd-only, since other distros might have the same issue)

**Comment by aplanas** [comment]
@jsuchome In sle11 in started with /sbin/startproc and --quite parameter (no forking).  But I tested in with forking and works OK. So IMHO is a valid configuration for both SLE11 and SLE12

**Pull request merged**
