### PR TITLE
Switch to standard database by default

### PR DESCRIPTION
**Pull request by dirkmueller**
Juno seems to be reasonably good with PostgreSQL support and
we have quite some unresolved security and maintenance issues
with mongodb.

### CODE REVIEW

**Comment by jsuchome** [comment]
Have we really tested it? I assume most of Cloud 5 deployments were with the default setting...

**Comment by tboerger** [comment]
Codewise LGTM

**Comment by dirkmueller** [comment]
@jsuchome yes, it seems to work for me (not extensively tested though)

**Comment by jsuchome** [comment]
Good. I was just wondering if it isn't too surprising change too late in the development.

**Comment by rsalevsky** [comment]
:+1: I assume this is still valid for Cloud 6.

**Comment by jsuchome** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
Let's try it for Cloud 6.

**Pull request merged**
